### ISSUE TITLE
User admin not created

### ISSUE THREAD

**Issue by xisberto** [opf/helm-charts#92]
Admin user is not created after deploy from helm.

Tried to execute the rake:seed command, but also to no avail.

On the database, there's an entry on table users with lastname 'System', but no login, and the user_passwords table is empty.

**Comment by nataz77** [comment]
+1

**Comment by oliverguenther** [comment]
Could you please add the log output of the seeder job? I suspect there's an issue with seeding the database

**Comment by AdamJSoftware** [comment]
Same issue here. Not sure how to even access the rails console to begin with which is an issue

**Comment by AdamJSoftware** [comment]
Further investigation, I found that the issue has to do with using an s3 bucket as storage as it fails with:
```Caused by:
2024-03-18T00:31:11.244771909Z Resolv::ResolvError: no address for openproject.mycustoms3bucket.com (Resolv::ResolvError)
2024-03-18T00:31:11.244775669Z /usr/local/bundle/gems/excon-0.109.0/lib/excon/socket.rb:191:in `connect'
2024-03-18T00:31:11.244779189Z /usr/local/bundle/gems/excon-0.109.0/lib/excon/ssl_socket.rb:193:in `connect'
2024-03-18T00:31:11.244788369Z /usr/local/bundle/gems/excon-0.109.0/lib/excon/socket.rb:60:in `initialize'
2024-03-18T00:31:11.244791999Z /usr/local/bundle/gems/excon-0.109.0/lib/excon/ssl_socket.rb:10:in `initialize'
2024-03-18T00:31:11.244795559Z /usr/local/bundle/gems/excon-0.109.0/lib/excon/connection.rb:482:in `new'
2024-03-18T00:31:11.244799189Z /usr/local/bundle/gems/excon-0.109.0/lib/excon/connection.rb:482:in `socket'
2024-03-18T00:31:11.244802729Z /usr/local/bundle/gems/excon-0.109.0/lib/excon/connection.rb:121:in `request_call'
2024-03-18T00:31:11.244806299Z /usr/local/bundle/gems/excon-0.109.0/lib/excon/middlewares/mock.rb:57:in `request_call'
```

Here is my s3 config:

```
s3:
  auth:
    accessKeyId: redacted
    existingSecret: null
    secretAccessKey: redacted
    secretKeys:
      accessKeyId: accessKeyId
      secretAccessKey: secretAccessKey
  bucketName: openproject
  directUploads: true
  enabled: true
  endpoint: https://mycustoms3bucket.com
  host: null
  pathStyle: false
  region: null
  signatureVersion: 4
  use_iam_profile: false
```

Not sure why it's trying to put the bucket name in front and how to avoid that from happening

**Comment by AdamJSoftware** [comment]
After doing some digging I was able to fix the issue by setting pathStyle to true. More of a user error then a helm chart bug. After upgrading the chart, the seeder ran again and resolved the issue. However, I had an issue changing my password as "Lastname field must be set". I had to manually go into postgres and update the value myself. This issue should also be addressed

**Comment by oliverguenther** [comment]
Thanks for the update and sorry for late reply. Did you set `OPENPROJECT_SEED_ADMIN_USER_NAME` ? If so, to what value did you set this?
